Vagrant.configure("2") do |config|

	# Define the Machine Server
	config.vm.define "server" do |server|
	  server.vm.box = "bento/ubuntu-20.04-arm64"
	  server.vm.network "private_network", ip: "192.168.56.110"
	  server.vm.synced_folder ".", "/vagrant"
	  server.vm.hostname = "lseiberrS"
	  server.vm.provider "parallels" do |parallels|
		parallels.memory = "2048"
		parallels.cpus = 2
	  end
	  server.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "/home/vagrant/.ssh/authorized_keys"
	  server.vm.provision "shell", path: "controller.sh"
	end
end
